# Base configs
baseurl: "https://gallery.kev1nweng.space"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Gallery"
subtitle: "Gallery"
author: "kW"
header:
 title: "kW"
 subtitle: "Gallery"
footer:
 name: "Hey there 👋"
 bio: "欢迎来到 The kW Gallery. "
 github: "此网页基于 <a href=\"https://github.com/ramswaroop/photography\">rampatra/photography</a> ;)"
web_design: "kW"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: "https://www.github.com/kev1nweng"
